Measure local cache size growth
gradle/gradle-profiler pull request #477
Opened 2023-02-06 14:07 UTC by lptr

When tests use the local cache, its size can grow. We want to capture that information in the benchmarks.

2023-02-07 17:08 UTC, asodja approved these changes
LGTM

2023-02-07 17:08 UTC, asodja commented on src/main/java/org/gradle/profiler/mutations/ShowBuildCacheSizeMutator.java
> +            long size = 0;
💭 Maybe this could be:
```
long size = Stream.of(cacheFiles).mapToLong(File::length).sum()
```

2023-02-07 17:17 UTC, asodja requested changes
❓ I noticed build cache size is always reported zero, is that just for me?

```
* Running measured build #25
Execution time 1112 ms
> Build cache size: 0 bytes in 0 file(s) (build-cache-1)
> Build cache size: 0 bytes in 0 file(s) (build-cache-2)

* Running measured build #26
Execution time 1480 ms
> Build cache size: 0 bytes in 0 file(s) (build-cache-1)
> Build cache size: 0 bytes in 0 file(s) (build-cache-2)
```

2023-02-07 20:45 UTC, lptr commented on subprojects/build-operations/src/main/java/org/gradle/trace/buildops/BuildOperationTrace.java
> +            cacheDirectories.forEach(cacheDirectory -> {
Alright, I'll bite :)

2023-02-07 20:53 UTC, lptr commented
Are you running a build without the build cache being enabled?

2023-02-07 20:56 UTC, lptr commented on src/main/java/org/gradle/profiler/mutations/ShowBuildCacheSizeMutator.java
> +            long size = 0;
Done.

2023-02-08 08:31 UTC, lptr commented
I added a test for `show-build-cache-size`.

2023-02-09 09:59 UTC, asodja approved these changes
LGTM

2023-02-09 09:59 UTC, asodja commented on src/main/java/org/gradle/profiler/result/DurationSample.java
> +        return extractTotalDurationFrom(result).toNanos() / 1_000_000d;
🧐 Does Duration has .toMillis(), to just do `extractTotalDurationFrom(result).toMillis()`?

2023-02-11 21:09 UTC, lptr commented
Well spotted fixes, thanks!

2023-02-11 21:09 UTC, merged